# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-12 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('longitud', models.CharField(max_length=20)),
                ('latitud', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estacion de servicio',
                'verbose_name_plural': 'Estaciones de servicio',
            },
        ),
        migrations.CreateModel(
            name='EstacionCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Estacion')),
            ],
            options={
                'verbose_name': 'Combustible de estacion',
                'verbose_name_plural': 'Combustibles de estaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de combustible',
                'verbose_name_plural': 'Tipos de combustible',
            },
        ),
        migrations.AddField(
            model_name='estacioncombustible',
            name='tipo_combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.TipoCombustible'),
        ),
        migrations.AlterUniqueTogether(
            name='estacioncombustible',
            unique_together=set([('estacion', 'tipo_combustible', 'valor')]),
        ),
    ]
